// Code generated by "stringer -type=EdgePrinciple"; DO NOT EDIT.

package types

import "strconv"

const _EdgePrinciple_name = "TRUEFALSE"

var _EdgePrinciple_index = [...]uint8{0, 4, 9}

func (i EdgePrinciple) String() string {
	if i < 0 || i >= EdgePrinciple(len(_EdgePrinciple_index)-1) {
		return "EdgePrinciple(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EdgePrinciple_name[_EdgePrinciple_index[i]:_EdgePrinciple_index[i+1]]
}
